blog/urls.py
# coding=utf-8
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
]

# 使用(?P<>\d+)的形式捕获值给<>中得参数，
# 比如(?P<article_id>\d+)，当访问/blog/article/3时，
# 将会将3捕获给article_id,这个值会传到views.ArticleDetailView,
# 这样我们就可以判断展示哪个Article了

qqq/urls.py
# coding:utf-8
"""qqq URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    ]

# namespace参数为我们指定了命名空间，说明这个urls.py中的url是blog app下的，
# 这样不同的app下有相同url也不会冲突。

blog/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from collections import defaultdict

import datetime

'''
所有的model必须继承django.db.models
类Article即表示Blog的文章
一个类被django映射成数据库中对应的一个表,类名即表名
类的属性(field),比如下面的title,body等对应着数据库的表的属性列
'''


class ArticleManage(models.Manager):  # 继承自默认的manager，为其添加一个自定义的archive方法
    def archive(self):
        date_list = Article.objects.datetimes('create_time', 'month', order='DESC')
        # 获取到降序排列的精确到月份且已去重和文章发表时间列表
        # 并把列表转为一个字典，字典的键为年份，值为年份下对应的月份列表
        date_dict = defaultdict(list)
        for d in date_list:
            date_dict[d.year].append(d.month)
        # 模版并不支持defaultdict，因此我们把它转换成一个二级列表，由于字典转换后无序，所以重新降序排序
        return sorted(date_dict.items(), reverse=True)


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    # 在status时说明
    objects = ArticleManage()

    title = models.CharField(u'标题', max_length=80)
    '''
    文章标题，CharField 表示对应数据库中表的列是用来存字符串的。
    '标题'是一个位置参数（verbose_name）。
    max_length 表示能存储的字符串的最大长度。
    '''

    body = models.TextField(u'正文')
    # 正文 TextField用来存储大文本字符

    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    # 文章创建时间 DateTimeField用于存储时间，设定auto_now_add参数为真，则在文章被创建时会自动添加创建时间

    last_modified_time = models.DateTimeField(u'修改时间', auto_now=True)
    # 文章最后修改时间 auto_now=True表示每次修改文章时自动添加修改的时间

    status = models.CharField(u'文章状态', max_length=1, choices=STATUS_CHOICES)
    '''
    STATUS_CHOICES,field的choices参数需要的值，
    choices选项会使该field在被渲染成form时被渲染成一个select组件，
    这里有两个状态，一个为Draft（草稿），一个为Published（已发送）
    即select组件有两个选项：Draft and Publish。
    但是存储在数据库中的值分别为‘d’ and ‘p’，这就是choices的作用
    '''

    abstract = models.CharField(u'摘要', max_length=70, blank=True, null=True,
                                help_text=u'可选，若为空将摘取正文的前54个字符')
    # 文章摘要，help_text在该field被渲染成form时显示帮助信息

    views = models.PositiveIntegerField(u'浏览量', default=0)
    # 浏览量，PositiveIntegerFied存储类型为非负整数

    likes = models.PositiveIntegerField(u'点赞数', default=0)
    # 点赞数，同上

    topped = models.BooleanField(u'置顶', default=False)
    # 是否置顶，BooleanField存储布尔值，默认为False（否）

    category = models.ForeignKey('Category', verbose_name=u'分类',
                                 null=True,
                                 on_delete=models.SET_NULL)
    '''
    文章的分类，ForeignKey即数据库中的外键。外键的定义是：如果数据库中某个表的列的值是另外一个表的主键。
    外键定义了一个一对多的关系，这里即一篇文章对应一个分类，而一个分类下可能有多篇文章。
    on_delete=models.SET_NULL表示删除某个分类（category）后该分类下所有的Article的外键设为null（空）

    '''

    tags = models.ManyToManyField('Tag', verbose_name=u'标签集合', blank=True)

    def get_absolute_url(self):
        return reverse('blog: detail', kwargs={'article_id': self.pk})

    def __unicode__(self):        # 用于交互解释器显示表示该类的字符串
        return self.title

    class Meta:
        # Meta包含一系列选项，这里的ordering表示排序，-号表示逆序。即当从数据库中取出文章时，是按文章最后一次修改时间逆序排列的。
        ordering = ['-last_modified_time']


class Category(models.Model):       # 另一个表，存储文章的分类信息
    name = models.CharField(u'类名', max_length=20)
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField(u'最后修改时间', auto_now=True)

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(u'标签名', max_length=25)
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField(u'最后修改时间', auto_now=True)

    def __unicode__(self):
        return self.name


class BlogComment(models.Model):
    user_name = models.CharField(u'评论者名字', max_length=100)
    user_email = models.EmailField(u'评论者邮箱', max_length=255)
    body = models.TextField(u'评论内容')
    created_time = models.DateTimeField(u'评论发表时间', auto_now_add=True)
    article = models.ForeignKey('Article', verbose_name=u'评论所属文章', on_delete=models.CASCADE)

    def __unicode__(self):
        return self.body[:20]

blog/forms.py
# coding=utf-8
from django import forms
from .models import Article, BlogComment


class BlogCommentForm(forms.ModelForm):

    class Meta:
        """指定一些 Meta 选项以改变 form 被渲染后的样式"""
        model = BlogComment  # form 关联的 Model

        fields = ['user_name', 'user_email', 'body',]
        # fields 表示需要渲染的字段，这里需要渲染user_name、user_email、body
        # 这样渲染后表单会有三个文本输入框，分别是输入user_name、user_email、body的输入框

        widgets = {
            # 为各个需要渲染的字段指定渲染成什么html组件，主要是为了添加css样式。
            # 例如 user_name 渲染后的html组件如下：
            # <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">

            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入昵称",
                'aria-describedby': "sizing-addon1",
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入邮箱",
                'aria-describedby': "sizing-addon1",
            }),
            'body': forms.Textarea(attrs={'placeholder': '我来评两句~'}),
        }

blog/views.py
# coding:utf-8
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, FormView
from blog.models import Article, Category, Tag
import markdown2
from .models import BlogComment
from .forms import BlogCommentForm


class IndexView(ListView):

    # 首页视图，继承自ListView,用于展示从数据库中获取的文章列表

    template_name = "blog/index.html"
    # template_name属性用于指定使用哪个模版进行渲染

    context_object_name = "article_list"
    # context_object_name属性用于给上下文变量取名（在模版中使用该名字）

    def get_queryset(self):

        # 过滤数据，获取所有已发布的文章，并且将内容转成markdown形式

        article_list = Article.objects.filter(status='p')
        # 获取数据库中的所有已发布的文章，即filter(过滤)状态为'p'(已发布)的文章。
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
            # 将markdown标记的文本转为html文本
        return article_list

    def get_context_data(self, **kwargs):
        # 增加额外的数据，这里返回一个文章分类，以字典的形式
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        # 调用archive方法，把获取到的时间列表插入到context上下文中以便在模版中渲染
        kwargs['tag_list'] = Tag.objects.all().order_by('name')  # tag_list加入context里
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    # Django有基于类的视图DetailView，用于显示一个对象的详情页，继承即可用
    model = Article
    # 指定视图获取哪个model

    template_name = "blog/detail.html"
    # 指定要渲染的模版文件

    context_object_name = "article"
    # 在模版中需要使用的上下文名字

    pk_url_kwarg = 'article_id'
    # pk_url_kwarg用于接收一个来自url中的主键，然后根据这个主键进行查询
    # 在urlpatters中已经捕获这个article_id

    # 指定以上几个属性，已经能返回一个DetailView视图，为了让文章以markdown形式展现需重写get_object()方法
    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'], )
        return obj

    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()
        kwargs['form'] = BlogCommentForm()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(ListView):          # 继承子ListView，用于展示一个列表

    template_name = "blog/index.html"
    # 指定需要渲染的模版

    context_object_name = "article_list"
    # 指定模版中需要使用的上下文对象的名字

    def get_queryset(self):  #
        article_list = Article.objects.filter(category=self.kwargs['cate_id'], status='p')
        # 在url里捕获分类的id作为关键字参数（cate_id）传递给了CategoryView，传递的参数在kwargs属性中获取。

        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):    # 给视图曾加额外数据
        kwargs['category_list'] = (Category.objects.all().order_by('name'))
        # 增加一个category_list，用于在页面显示所有分类，按照名字排序
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):     # 根据指定的标签获取该标签下的全部文章
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)


class ArchiveView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):     # 接收从url传递的year和month参数，转换成int类型
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        # 按照year和month过滤文章
        article_list = Article.objects.filter(create_time_year=year, create_time__month=month)
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all.order_by('name')
        return super(ArchiveView, self).get_context_data(**kwargs)


class CommentPostView(FormView):
    form_class = BlogCommentForm
    template_name = 'blog/detail.html'

    def form_invalid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        comment = form.save(commit=False)
        comment.article = target_article
        comment.save()
        self.success_url = target_article.get_absolute_url()
        return HttpResponseRedirect(self.success_url)

    def form_valid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        return render(self.request, 'blog/detail.html', {
            'form': form,
            'article': target_article,
            'comment_list': target_article.blogcomment_set.all(),
        })

blog/templates/blog/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>
</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">首页</a></li>
                            <li>&gt;</li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title=""
                                           rel="category">{{ article.category.name }}</a>
                                    </li>
                                </ul>
                            </li>
                            <li>&gt;</li>
                            <li class="title-active"><a href="{% url 'blog:detail' article.pk %}"
                                                        rel="bookmark">{{ article.title }}</a>
                            </li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            {% for category in category_list %}
                                <li class="cat-item"><a
                                        href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% load paginate_tags %}
                        {% paginate article_list 2 %}
                        {% for article in article_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title"><a
                                            href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h1>
                                </div>
                                <div class="post-bd">
                                    <!-- 	<p><a href=""><img src="" alt=""></a></p> -->
                                    <p>{{ article.abstract }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="{% url 'blog:detail' article.id %}" class="more">阅读全文>></a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>标签:</h3>
                <div class="list-group">

                </div>

                <!-- archive -->
                <h3>文章归档：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <div id="pagenavi" class="noselect">
    {% if article_list.has_previous %} # 判断是否还有上一页，有的话要显示一个上一页按钮
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    # 页码号为1永远显示
    {% if first_page == current_page %} # 当前页就是第一页
        <span class="first-page current">1</span>
    {% else %} # 否则的话，第一页是可以点击的，点击后通过?page=1的形式把页码号传递给视图函数
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %} # 2以前的页码号要被显示成省略号了
        <span>...</span>
    {% endif %}

    {% for page in pages %} # 通过for循环把pages中的值显示出来
        {% if page == current_page %} # 是否当前页，按钮会显示不同的样式
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

      # pages最后一个值+1的值小于最大页码号，说明有页码号需要被省略号替换
    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

      # 永远显示最后一页的页码号，如果只有一页则前面已经显示了1就不用再显示了
    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    # 还有下一页，则显示一个下一页按钮
    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
    </div>
</body>
</html>